apiVersion: v1
kind: Service
metadata:
  labels:
    app: webserver
  name: web-deployment
spec:
  selector:
    app: webserver
  type: NodePort
  ports:
  - nodePort: {{ .Values.service.ports.nodeport }}
    port: {{ .Values.service.ports.port }}
    protocol: TCP
    targetPort: {{ .Values.service.ports.targetport }}
