# this is used to not exceed the usage of the resources to the namespaces.
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resource-quota
spec:
  hard:
    cpu: {{ .Values.resourcequota.spec.cpu }}
    memory: {{ .Values.resourcequota.spec.memory }}
    pods: {{ .Values.resourcequota.spec.pods }}
