apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: webserverscale
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web-deployment
  minReplicas: {{ .Values.webserverAutoScaling.minReplicas }}
  maxReplicas: {{ .Values.webserverAutoScaling.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.webserverAutoScaling.metrics.averageUtilization }}
