apiVersion: v1
kind: Service
metadata:
  labels:
    app: webserver
  name: web-deployment
spec:
  selector:
    app: webserver
  type: NodePort
  ports:
  - nodePort: 30500
    port: 80
    protocol: TCP
    targetPort: 80
