apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  labels:
    app: webserver
spec:
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
      - name: appserver
        image: nandu9948/apacheserver
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 40
          timeoutSeconds: 60
          periodSeconds: 10
          failureThreshold: 1
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 600
          failureThreshold: 1
        resources:
          requests:
            memory: "10Mi"
            cpu: "50m"
          limits:
            memory: "15Mi"
            cpu: "90m"

